[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  version = "v1.28.4"
  name = "github.com/aws/aws-sdk-go"
