nameOverride: ""
fullnameOverride: ""

service:
  port: 8234

image:
  repository: flowcommerce/aws-credentials-broker
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "50Mi"
    cpu: .05

nodeSelector: {}
affinity: {}
tolerations: {}

ingress:
  enabled: true
  gateways:
    - key: aws-credentials-broker-flow-io
      tld: flow.io
      hosts:
        - aws-credentials-broker.flow.io

services:
  live:
    hosts:
      - aws-credentials-broker
      - aws-credentials-broker.flow.io
    gateways:
      - mesh
      - aws-credentials-broker-flow-io
    stages:
      - deployment: live
        weight: 100

deployments:
  live:
    minReplicas: 2
    maxReplicas: 2
    maxUnavailable: 1
    disruptionBudgetEnabled: true
    targetCPUUtilizationPercentage: 80
    version: master-1